## thanks to https://dzone.com/articles/continuous-integration-windows
## with some adjustments and exported yaml-settings

version: '{build}'
os: Windows Server 2012

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

build_script:
  - gradlew.bat clean assemble install --info --no-daemon --stacktrace

test_script:
  - gradlew.bat check --info --no-daemon --stacktrace

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9

matrix:
  fast_finish: true
